blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blog.apps import BlogConfig
from users.apps import UsersConfig

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('email_sends.urls')),
    path('users/', include('users.urls', namespace=UsersConfig.name)),
    path('blog/', include('blog.urls', namespace=BlogConfig.name)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

email_sends/urls.py
from django.urls import path

from email_sends.apps import EmailSendsConfig
from email_sends.views import ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView, \
    MessageListView, MessageDetailView, MessageUpdateView, MessageDeleteView, MessageCreateView, \
    MailingSettingsListView, MailingSettingsDetailView, MailingSettingsUpdateView, MailingSettingsDeleteView, \
    MailingSettingsCreateView, MailingLogListView
from email_sends.views.home import home

app_name = EmailSendsConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='edit_client'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='delete_client'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),

    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('messages/<int:pk>/edit/', MessageUpdateView.as_view(), name='edit_message'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='delete_message'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),

    path('mailings/', MailingSettingsListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>', MailingSettingsDetailView.as_view(), name='mailing_detail'),
    path('mailings/<int:pk>/edit/', MailingSettingsUpdateView.as_view(), name='edit_mailing'),
    path('mailings/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='delete_mailing'),
    path('mailings/create/', MailingSettingsCreateView.as_view(), name='create_mailing'),

    path('logs/', MailingLogListView.as_view(), name='log_list'),
]

email_sends/models.py
from django.db import models
from django.utils.datetime_safe import datetime

from users.models import User


class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name="ФИО")
    email = models.EmailField(unique=True, verbose_name="email")
    comment = models.CharField(max_length=200, null=True, blank=True, verbose_name="комментарий")
    creator = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Создатель")

    def __str__(self):
        return f"{self.name} ({self.email})"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"


class Message(models.Model):
    theme = models.CharField(max_length=200, verbose_name="Тема письма")
    body = models.TextField(verbose_name="Текст письма")
    creator = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Создатель")

    def __str__(self):
        return f"{self.theme}"

    class Meta:
        verbose_name = "сообщение для рассылки"
        verbose_name_plural = "сообщения для рассылки"


class MailingSettings(models.Model):
    EVERY_DAY = "EVERY_DAY"
    EVERY_WEEK = "EVERY_WEEK"
    EVERY_MONTH = "EVERY_MONTH"

    CREATED = "CREATED"
    FINISHED = "FINISHED"
    STARTED = "STARTED"

    MAILING_FREQUENCY_CHOICES = ((EVERY_DAY, "Раз в день"),
                                 (EVERY_WEEK, "Раз в неделю"),
                                 (EVERY_MONTH, "Раз в месяц"))

    MAILING_STATUS_CHOICES = ((CREATED, "Создана"),
                              (FINISHED, "Завершена"),
                              (STARTED, "Запущена"))

    name = models.CharField(max_length=200, verbose_name="Название рассылки")
    start_at = models.DateTimeField(default=datetime.now, verbose_name="Дата и время начала рассылки")
    stop_at = models.DateTimeField(null=True, blank=True, verbose_name="Дата и время окончания рассылки")
    frequency = models.CharField(choices=MAILING_FREQUENCY_CHOICES, max_length=200,
                                 verbose_name="Периодичность рассылки", default=EVERY_DAY)
    status = models.CharField(choices=MAILING_STATUS_CHOICES, max_length=200, default=CREATED,
                              verbose_name="Статус рассылки")

    clients = models.ManyToManyField(Client, verbose_name="Клиенты", blank=True, related_name="mailing_settings", )
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="Сообщение для рассылки",
                                related_name="mailing_settings")

    creator = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Создатель")

    def __str__(self):
        return (f"{self.name}. Тема: {self.message.theme}, периодичность "
                f"'{self.get_frequency_display()}'.")

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [
            ('can_change_status', 'может менять статус')
        ]
        ordering = ["id"]


class MailingLog(models.Model):
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    MAILING_LOG_STATUS_CHOICES = ((SUCCESS, "Успешно"), (ERROR, "Ошибка"))

    last_sent = models.DateTimeField(auto_now_add=True, verbose_name="Дата/время последней попытки отправки")
    status = models.CharField(choices=MAILING_LOG_STATUS_CHOICES, max_length=200, verbose_name="Статус отправки")
    server_response = models.TextField(null=True, blank=True, verbose_name="Ответ почтового сервера")
    mailing = models.OneToOneField(MailingSettings, on_delete=models.CASCADE, verbose_name="Рассылка",
                                   related_name="mailing_log")

    def __str__(self):
        return (f"{self.mailing.name}. Статус: {self.get_status_diplay()}. "
                f"Дата/время последней попытки отправки: {self.last_sent}")

    class Meta:
        verbose_name = "Лог рассылки"
        verbose_name_plural = "Логи рассылки"

email_sends/forms.py
from django.forms import ModelForm

from email_sends.models import MailingSettings
from users.forms import StyleFormMixin


class ManagerUpdateMailingSettingsForm(StyleFormMixin, ModelForm):
    class Meta:
        model = MailingSettings
        fields = ["status"]

email_sends/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from email_sends.models import Client


class ClientListView(ListView):
    model = Client
    paginate_by = 10


class ClientCreateView(CreateView):
    model = Client

    fields = ['name', 'email', 'comment']
    success_url = reverse_lazy('email_sends:client_list')


class ClientUpdateView(UpdateView):
    model = Client
    fields = ['name', 'email', 'comment']
    success_url = reverse_lazy('email_sends:client_list')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('email_sends:client_list')


class ClientDetailView(DetailView):
    model = Client

email_sends/views/clients.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from email_sends.models import Client
from email_sends.views.mailing import IsCouldBeChangedMixin, IsCouldBeDetailMixin


class ClientListView(ListView):
    model = Client
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_anonymous:
            return self.model.objects.none()
        return super().get_queryset().filter(creator=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client

    fields = ['name', 'email', 'comment']
    success_url = reverse_lazy('email_sends:client_list')

    def form_valid(self, form):
        if form.is_valid():
            client = form.save()
            client.creator = self.request.user
            client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, IsCouldBeChangedMixin, UpdateView):
    model = Client
    fields = ['name', 'email', 'comment']
    success_url = reverse_lazy('email_sends:client_list')


class ClientDeleteView(LoginRequiredMixin, IsCouldBeChangedMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('email_sends:client_list')


class ClientDetailView(IsCouldBeDetailMixin, DetailView):
    model = Client

email_sends/views/home.py
from django.shortcuts import render

from blog.services import get_last_three_articles
from email_sends.services import get_mailings_count, get_active_mailings_count, get_clients_count


def home(request):
    """endpoint для главной страницы"""

    return render(request, 'email_sends/index.html', context={
        "articles": get_last_three_articles(),
        "mailings_count": get_mailings_count(),
        "active_mailings_count": get_active_mailings_count(),
        "clients_count": get_clients_count()
    })

email_sends/views/mailing.py
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from email_sends.forms import ManagerUpdateMailingSettingsForm
from email_sends.models import MailingSettings, Message, Client
from email_sends.services import process_mailing


# from email_sends.services import process_mailing
class IsCouldBeChangedMixin:
    def get_form_class(self):
        if self.request.user == self.get_object().creator:
            return super().get_form_class()
        raise PermissionDenied


class IsCouldBeDetailMixin:
    def get_context_data(self, **kwargs):
        if self.request.user == self.get_object().creator or self.request.user.is_manager:
            return super().get_context_data(**kwargs)
        raise PermissionDenied


class MailingSettingsListView(ListView):
    model = MailingSettings
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_anonymous:
            return self.model.objects.none()
        if self.request.user.is_manager:
            return super().get_queryset()
        return super().get_queryset().filter(creator=self.request.user)


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings

    fields = ['name', 'start_at', 'stop_at', 'frequency', 'clients', 'message']
    success_url = reverse_lazy('email_sends:mailing_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'].fields['message'].queryset = Message.objects.filter(creator=self.request.user)
        context['form'].fields['clients'].queryset = Client.objects.filter(creator=self.request.user)
        return context

    def get_form(self, form_class=None):
        """add date picker in forms"""
        form = super(MailingSettingsCreateView, self).get_form(form_class)
        form.fields['start_at'].widget = forms.DateTimeInput(format="%Y-%m-%d %H:%M", attrs={"type": "datetime-local"})
        form.fields['stop_at'].widget = forms.DateTimeInput(format="%Y-%m-%d %H:%M", attrs={"type": "datetime-local"})

        return form

    def form_valid(self, form):
        if form.is_valid():
            mailing = form.save()
            mailing.creator = self.request.user
            mailing.save()
            process_mailing(mailing)  # отправка рассылки при необходимости
        return super().form_valid(form)


class MailingSettingsUpdateView(LoginRequiredMixin, IsCouldBeChangedMixin, UpdateView):
    model = MailingSettings
    fields = ['name', 'start_at', 'stop_at', 'frequency', 'clients', 'message']
    success_url = reverse_lazy('email_sends:mailing_list')

    def get_form_class(self):
        if self.request.user == self.get_object().creator:
            return super().get_form_class()
        if self.request.user.is_manager:
            return ManagerUpdateMailingSettingsForm
        raise PermissionDenied

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.creator == self.request.user:
            context['form'].fields['message'].queryset = Message.objects.filter(creator=self.request.user)
            context['form'].fields['clients'].queryset = Client.objects.filter(creator=self.request.user)
        return context

    def get_form(self, form_class=None):
        """add date picker in forms"""
        form = super(MailingSettingsUpdateView, self).get_form(form_class)
        if self.object.creator == self.request.user:
            form.fields['start_at'].widget = forms.DateTimeInput(format="%Y-%m-%d %H:%M",
                                                                 attrs={"type": "datetime-local"})
            form.fields['stop_at'].widget = forms.DateTimeInput(format="%Y-%m-%d %H:%M",
                                                                attrs={"type": "datetime-local"})

        return form


class MailingSettingsDeleteView(LoginRequiredMixin, IsCouldBeChangedMixin, DeleteView):
    model = MailingSettings
    success_url = reverse_lazy('email_sends:mailing_list')


class MailingSettingsDetailView(IsCouldBeDetailMixin, DetailView):
    model = MailingSettings

email_sends/views/mailing_logs.py
from django.views.generic import ListView

from email_sends.models import MailingLog


class MailingLogListView(ListView):
    model = MailingLog
    paginate_by = 10
    ordering = ['-last_sent']

email_sends/views/messages.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from email_sends.models import Message
from email_sends.views.mailing import IsCouldBeChangedMixin, IsCouldBeDetailMixin


class MessageListView(ListView):
    model = Message
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_anonymous:
            return self.model.objects.none()
        return super().get_queryset().filter(creator=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message

    fields = ['theme', 'body']
    success_url = reverse_lazy('email_sends:message_list')

    def form_valid(self, form):
        if form.is_valid():
            message = form.save()
            message.creator = self.request.user
            message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, IsCouldBeChangedMixin, UpdateView):
    model = Message
    fields = ['theme', 'body']
    success_url = reverse_lazy('email_sends:message_list')


class MessageDeleteView(LoginRequiredMixin, IsCouldBeChangedMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('email_sends:message_list')


class MessageDetailView(IsCouldBeDetailMixin, DetailView):
    model = Message

email_sends/templates/email_sends/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">


    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>
</head>
<body>


<main>

    <div class="container">
        <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
                <li class="nav-item"><a href="{% url 'email_sends:home' %}" class="nav-link"
                                        aria-current="page">Главная</a></li>
                <li class="nav-item"><a href="{% url 'email_sends:client_list' %}" class="nav-link">Клиенты</a></li>
                <li class="nav-item"><a href="{% url 'email_sends:message_list' %}" class="nav-link">Сообщения</a></li>
                <li class="nav-item"><a href="{% url 'email_sends:mailing_list' %}" class="nav-link">Рассылки</a></li>
                <li class="nav-item"><a href="{% url 'email_sends:log_list' %}" class="nav-link">Отчёты</a></li>
                {% if user.is_manager %}
                <li class="nav-item"><a href="{% url 'users:user-list' %}" class="nav-link">Пользователи</a></li>
                {% endif %}
            </ul>
            <div class="col-md-3 text-end">
                {% if user.is_authenticated %}
                <a class="btn btn-outline-primary me-2" href="{% url 'users:user-profile'%}">Профиль</a>
                <a class="btn btn-outline-primary me-2" href="{% url 'users:logout'%}">Выход</a>
                {% else %}
                <a class="btn btn-outline-primary me-2" href="{% url 'users:login'%}">Вход</a>
                <a class="btn btn-primary" href="{% url 'users:register'%}">Регистрация</a>
                {% endif %}
            </div>
        </header>
        <div class="container-fluid">
            {% block content %}
            <div class="text-center">
                Добро пожаловать на сайт сервиса управления email-рассылками.
            </div>
            {% endblock %}
        </div>
    </div>


</main>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

email_sends/templates/email_sends/client_confirm_delete.html
{% extends 'email_sends/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Удаление данных клиента:</h5>
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить "{{ object }}"?</p>
                    {{ form.as_div }}
                    <div class="btn-group">
                        <button type="submit" class="btn btn-primary">Удалить</button>
                        <a href="{% url 'email_sends:client_list' %}" class="btn btn-outline-secondary">Отменить</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

email_sends/templates/email_sends/client_detail.html
{% extends 'email_sends/base.html' %}

{% block content %}

<div class="card col-6">
    <div class="card-body">
        <h5 class="card-title">
            {{ object.name }}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">Email: {{ object.email }}</h6>
        {% if object.comment %}
        <div class="card-text">
            Комментарий: {{ object.comment }}
        </div>
        {% endif %}
        <div class="btn-group">
            <a class="btn btn-primary" href="{% url 'email_sends:edit_client' object.id %}">Редактировать</a>
            <a class="btn btn-primary" href="{% url 'email_sends:delete_client' object.id %}">Удалить</a>
        </div>
    </div>
</div>
{% endblock %}

email_sends/templates/email_sends/client_form.html
{% extends 'email_sends/base.html' %}

{% block content %}

<div class="card col-6">
    <div class="card-body">
        <h5 class="card-title">
            {% if object %}
            Редактирование данных клиента
            {% else %}
            Создание клиента
            {% endif %}</h5>
        <div class="card-text">
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <a href="{% url 'email_sends:client_list' %}" class=" btn btn-outline-secondary">Отменить</a>
                {% if object %}

                <input type="submit" class="btn btn-primary" value="Сохранить">
                {% else %}
                <input type="submit" class="btn btn-primary" value="Создать">
                {% endif %}
            </form>
        </div>

    </div>
</div>
{% endblock %}

email_sends/templates/email_sends/mailinglog_list.html
{% extends 'email_sends/base.html' %}

{% block content %}


<div class="row">
    <div class="col-12">
        <div class="card" style="border:none">
            <div class="card-body">
                <h5 class="card-title">Отчеты:</h5>
                {% if page_obj|length %}
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Дата/время последней отправки</th>
                        <th scope="col">Название рассылки</th>
                        <th scope="col">Клиенты</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Ответ почтового сервера</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for log in page_obj %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ log.last_sent }}</td>
                        <td>{{ log.mailing.name }}</td>
                        <td>{{ log.mailing.clients.all|join:', ' }}</td>
                        <td>{{ log.get_status_display }}</td>
                        <td>{% if log.server_response %}
                            {{ log.server_response }}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>
                {% if page_obj.paginator.num_pages > 1 %}
                <nav aria-label="Logs navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"
                                                 title="Назад">
                            <span aria-hidden="true">&laquo;</span>
                        </a></li>
                        {% endif %}

                        <li class="page-item current"><span class="current page-link"> Страница {{ page_obj.number }} из
                    {{ page_obj.paginator.num_pages }}</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                                 aria-label="Next" title="Вперёд">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
                {% else %}
                Пока нет данных.
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

email_sends/templates/email_sends/mailingsettings_confirm_delete.html
{% extends 'email_sends/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Удаление рассылки:</h5>
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить "{{ object }}"?</p>
                    {{ form.as_div }}
                    <div class="btn-group">
                        <button type="submit" class="btn btn-primary">Удалить</button>
                        <a href="{% url 'email_sends:mailing_list' %}" class="btn btn-outline-secondary">Отменить</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

email_sends/templates/email_sends/mailingsettings_detail.html
{% extends 'email_sends/base.html' %}

{% block content %}

<div class="card col-6">
    <div class="card-header">
        <h5 class="card-title">
            {{ object.name }}
        </h5>

    </div>
    <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">Дата/время начала: {{ object.start_at }}</h6>
        {% if object.stop_at %}
        <h6 class="card-subtitle mb-2 text-muted">Дата/время окончания: {{ object.stop_at }}</h6>
        {% endif %}
        <h6 class="card-subtitle mb-2 text-muted">Тема сообщения: {{ object.message.theme }}</h6>
    </div>
    <div class="card-header">
        <h5 class="card-title">Текст сообщения:</h5>
    </div>
    <div class="card-body">

        <div class="card-text">
            {{ object.message.body }}
        </div>


    </div>
    <div class="card-header">
        <h5 class="card-title">Клиенты:</h5>
    </div>
    <ul class="list-group list-group-flush">
        {% for client in object.clients.all %}
        <li class="list-group-item">{{ client }}</li>
        {% endfor %}
    </ul>
    {% if object.creator == user or user.is_manager %}
    <div class="card-body">
        <div class="btn-group mt-2">
            <a class="btn btn-primary" href="{% url 'email_sends:edit_mailing' object.id %}">Редактировать</a>
            {% if mailing.creator == user %}
            <a class="btn btn-primary" href="{% url 'email_sends:delete_mailing' object.id %}">Удалить</a>
            {% endif %}
        </div>
    </div>
    {% endif %}
    <div class="card-footer text-muted mt-2">
        Статус: '{{ object.get_status_display }}'
    </div>
    {% if object.creator %}
    <div class="card-footer text-muted mt-2">
        Автор: '{{ object.creator }}'
    </div>
    {% else %}
    <div class="card-footer text-muted mt-2">
        Автор: аноним.
    </div>
    {% endif %}
</div>
{% endblock %}

email_sends/templates/email_sends/mailingsettings_list.html
{% extends 'email_sends/base.html' %}

{% block content %}


<div class="row">
    <div class="col-12">
        <div class="card" style="border:none">
            <div class="card-body">
                <h5 class="card-title">Рассылки:</h5>
                {% if page_obj|length %}
                <a class="btn btn-primary mb-2" href="{% url 'email_sends:create_mailing'%}"
                   role="button">Добавить</a>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Название</th>
                        <th scope="col">Периодичность</th>
                        <th scope="col">Дата/время старта</th>
                        <th scope="col">Дата/время окончания</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Клиенты</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for mailing in page_obj %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ mailing.name }}</td>
                        <td>{{ mailing.get_frequency_display }}</td>
                        <td>{{ mailing.start_at }}</td>
                        <td>{% if mailing.stop_at %}
                            {{ mailing.stop_at }}
                            {% endif %}
                        </td>
                        <td>{{ mailing.get_status_display }}</td>
                        <td>
                            {{ mailing.clients.all|join:', ' }}
                        </td>
                        <td class="d-flex flex-wrap" style="gap: 2px">
                            <a class="btn btn-primary" href="{% url 'email_sends:mailing_detail' mailing.id  %}"
                               role="button">Подробнее</a>
                            {% if mailing.creator == user or user.is_manager %}
                            <a class="btn btn-primary" href="{% url 'email_sends:edit_mailing' mailing.id  %}"
                               role="button">Редактировать</a>
                            {% endif %}
                            {% if mailing.creator == user %}
                            <a class="btn btn-primary" href="{% url 'email_sends:delete_mailing' mailing.id %}"
                               role="button">Удалить</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>
                {% if page_obj.paginator.num_pages > 1 %}
                <nav aria-label="Mailings navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"
                                                 title="Назад">
                            <span aria-hidden="true">&laquo;</span>
                        </a></li>
                        {% endif %}

                        <li class="page-item current"><span class="current page-link"> Страница {{ page_obj.number }} из
                    {{ page_obj.paginator.num_pages }}</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                                 aria-label="Next" title="Вперёд">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
                {% else %}
                У вас пока нет созданных рассылок. <a class="btn btn-primary"
                                                      href="{% url 'email_sends:create_mailing'%}"
                                                      role="button">Создать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}